
--> Running on the CPU
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "/opt/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'upate_target_every'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/xunyijiang/Documents/StudyMaterials/2024Spring/AI planning/Project/RLProjectCode/GitHub/AIPlanningProject/src/training/dqn_training.py", line 63, in train
    update_target_every=args.upate_target_every,
  File "/opt/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'upate_target_every'